name: Sync Di√°rio

on:
  schedule:
    - cron: '0 8,14,20 * * *' # 08h, 14h e 20h UTC (ajuste para seu fuso)
  workflow_dispatch: {}

jobs:
   sync:
    runs-on: ubuntu-latest
    steps:
      - name: Criar run
        run: curl -X POST https://clientes-natiops.53rnlo.easypanel.host/sync/runs/full -H "Content-Type: application/json"
      - name: Processar run
        run: curl -X POST https://clientes-natiops.53rnlo.easypanel.host/sync/runs/full/process -H "Content-Type: application/json"
